---

- name: Enable PostgreSQL 15 module
  command: dnf module enable postgresql:15 -y
  become: true

- name: Install PostgreSQL
  dnf:
    name:
    - postgresql-server
    - postgresql-contrib
    - python3-psycopg2
    state: present
  become: true

- name: Initialize PostgreSQL database
  command: /usr/bin/postgresql-setup --initdb --unit postgresql
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: true

- name: Enable and start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Create database user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: true

- name: Create application database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: true

- name: Copy init.sql to server
  copy:
    src: ../db/init.sql
    dest: /tmp/init.sql
  become: true

- name: Run init.sql
  become_user: postgres
  command: psql -d {{ db_name }} -f /tmp/init.sql
