---
# tasks/main.yml for PostgreSQL role

- name: Install PostgreSQL 15 packages
  yum:
    name:
    - postgresql15
    - postgresql15-server
    - postgresql15-contrib
    state: present

- name: Initialize PostgreSQL 15 database cluster (idempotent)
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Ensure PostgreSQL data directory has proper ownership
  file:
    path: /var/lib/pgsql/data
    owner: postgres
    group: postgres
    state: directory
    recurse: yes

- name: Set PostgreSQL to listen on localhost (CRITICAL LISTEN FIX)
  lineinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#?listen_addresses =.*'
    line: "listen_addresses = 'localhost'"
    state: present

- name: Enable and start PostgreSQL service (AL2023 Standard Service Name)
  systemd:
    name: postgresql
    enabled: yes
    state: started
