---
- name: Install PostgreSQL 15 packages
  ansible.builtin.dnf:
    name:
    - postgresql15-server
    - postgresql15-contrib
    - python3-psycopg2
    state: present
  become: true

- name: Initialize PostgreSQL 15 database cluster (AL2023 Standard Command)
  ansible.builtin.command:
    # Use the standard wrapper command for the default AL2023 packages
    cmd: postgresql-setup --initdb
    # Use the standard data directory path
    creates: /var/lib/pgsql/data/postgresql.conf
  become: true

- name: Set correct permissions for PostgreSQL data directory (CRITICAL FIX)
  ansible.builtin.file:
    # Use the standard data directory path
    path: /var/lib/pgsql/data
    owner: postgres
    group: postgres
    recurse: true
    state: directory
  become: true

- name: Configure MD5 authentication for local connections (ROBUST INSERT FIX)
  ansible.builtin.lineinfile:
    # Use the standard data directory path
    path: /var/lib/pgsql/data/pg_hba.conf
    # The robust 'host all all 127.0.0.1/32 md5' line
    line: 'host all all 127.0.0.1/32 md5'
    insertbefore: "^host\\s+all\\s+all\\s+127\\.0\\.0\\.1\\/32\\s+(ident|peer)$"
    state: present
    backup: yes
  become: true
  notify: Restart PostgreSQL

- name: Set PostgreSQL to listen on localhost (CRITICAL LISTEN FIX)
  ansible.builtin.lineinfile:
    # Use the standard data directory path
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: '^#?listen_addresses\s*=\s*.*$'
    line: "listen_addresses = 'localhost'"
    backup: yes
  become: true
  notify: Restart PostgreSQL

- name: Enable and start PostgreSQL service (AL2023 Standard Service Name)
  ansible.builtin.systemd:
    # Use the standard service name
    name: postgresql
    state: started
    enabled: true
  become: true

# --- Database Configuration Tasks ---

- name: Create database user ({{ db_user }})
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: true
  become_user: postgres

- name: Copy init.sql to server
  ansible.builtin.copy:
    src: ../db/init.sql
    dest: /tmp/init.sql
    mode: '0644'
  become: true

- name: Run init.sql to populate the database
  # Run against the 'postgres' database to ensure we can run CREATE DATABASE
  ansible.builtin.shell: "psql -d postgres -f /tmp/init.sql"
  become: true
  become_user: postgres
... 