---

- name: Install PostgreSQL 15
  dnf:
    name:
    - postgresql15
    - postgresql15-server
    - postgresql15-contrib
    - python3-psycopg2
    state: present
  become: true

- name: Initialize PostgreSQL database
  command: /usr/bin/postgresql-15-setup initdb
  args:
    creates: /var/lib/pgsql/15/data/postgresql.conf
  become: true

- name: Enable and start PostgreSQL
  service:
    name: postgresql-15
    state: started
    enabled: true
  become: true

# - name: Initialize PostgreSQL database
#   command: /usr/bin/postgresql-setup --initdb --unit postgresql
#   args:
#     creates: /var/lib/pgsql/data/postgresql.conf
#   become: true

- name: Enable and start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Create database user
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: true

- name: Create application database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"
  become: true

- name: Copy init.sql to server
  copy:
    src: ../db/init.sql
    dest: /tmp/init.sql
  become: true

- name: Run init.sql
  become_user: postgres
  command: psql -d {{ db_name }} -f /tmp/init.sql
