---
# Assumes 'dnf' is the package manager (correct for Amazon Linux 2023)

- name: Install PostgreSQL 15 packages
  ansible.builtin.dnf:
    name:
    - postgresql15-server
    - postgresql15-contrib
    - python3-psycopg2 # Required for the postgresql_user/db modules
    state: present
  become: true

- name: Initialize PostgreSQL database cluster
  ansible.builtin.command:
    cmd: postgresql-setup --initdb
    creates: /var/lib/pgsql/data/postgresql.conf
  become: true

# ----------------- CRITICAL FIX: Simplified 'line' to prevent restart failure -----------------
- name: Set PostgreSQL to use MD5 password authentication for local connections
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    # Targets the default IPv4 local connection line and replaces 'ident' or 'peer' with 'md5'.
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1\/32\s+(ident|peer)$'
    # Use simple spacing for reliability (Fixes the service restart issue)
    line: 'host all all 127.0.0.1/32 md5'
    backup: yes
  become: true
  notify: Restart PostgreSQL
# --------------------------------------------------------------------------------------------

- name: Enable and start PostgreSQL service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
  become: true

# --- Database Configuration Tasks ---

- name: Create database user ({{ db_user }})
  ansible.builtin.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB,LOGIN
  become: true
  become_user: postgres

# --- TASK REMOVED: init.sql will now handle database creation ---

- name: Copy init.sql to server
  ansible.builtin.copy:
    src: ../db/init.sql
    dest: /tmp/init.sql
    mode: '0644'
  become: true

- name: Run init.sql to populate the database
  # CRITICAL FIX: Run against the 'postgres' default database 
  # which allows the script to run 'CREATE DATABASE' and '\c' commands.
  ansible.builtin.shell: "psql -d postgres -f /tmp/init.sql"
  become: true
  become_user: postgres
...
