---
- name: Install Node.js and npm
  yum:
    name: nodejs
    state: present

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Create Node.js app directory
  file:
    path: /opt/apps/node_app
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Copy Node.js app (assume you have code locally in repo)
  copy:
    src: ../../node_app/
    dest: /opt/apps/node_app/

- name: Create .env file
  copy:
    dest: /opt/apps/node_app/.env
    content: |
      DB_NAME={{ db_name }}
      DB_USER={{ db_user }}
      DB_PASSWORD={{ db_password }}
      DB_HOST=localhost
      PORT={{ node_port }}

- name: Install dependencies
  npm:
    path: /opt/apps/node_app
    state: present

- name: Start Node.js app with PM2
  command: pm2 start /opt/apps/node_app/app.js --name node_app --watch
  args:
    chdir: /opt/apps/node_app
