---
- name: Install Python, pip, and Gunicorn dependencies
  yum:
    name:
    - python3
    - python3-pip
    - python3-devel # Needed for psycopg2 compilation
    state: present

# We don't need to explicitly create the directory here if it's in site.yml pre_tasks,
# but keeping it doesn't hurt, so we'll leave it as a safe guard.
- name: Ensure Flask app directory exists
  file:
    path: /opt/apps/flask_app
    state: directory
    owner: ec2-user
    group: ec2-user

# --- ARTIFACT DEPLOYMENT ---
- name: Copy Flask artifact to server
  copy:
    # Use the relative path to the Jenkins workspace root
    src: "../{{ flask_artifact }}"
    dest: "{{ app_directory }}/" # Copies the .tar.gz file to /opt/apps/
    owner: ec2-user
    group: ec2-user
  when: flask_artifact != ""

- name: Extract Flask app
  unarchive:
    # Unarchives the file from the remote /opt/apps/ directory
    src: "{{ app_directory }}/{{ flask_artifact | basename }}"
    dest: /opt/apps/
    remote_src: true
    owner: ec2-user
    group: ec2-user
  when: flask_artifact != ""

- name: Install Flask dependencies (using requirements.txt from extracted artifact)
  pip:
    requirements: /opt/apps/flask_app/requirements.txt
    executable: pip3
  become: true
  when: flask_artifact != ""

- name: Create Flask .env file
  copy:
    dest: /opt/apps/flask_app/.env
    content: |
      DATABASE_HOST={{ db_host }}
      DATABASE_PORT={{ db_port }}
      DATABASE_NAME={{ db_name }}
      DATABASE_USER={{ db_user }}
      DATABASE_PASSWORD={{ db_password }}
      FLASK_PORT={{ flask_port }}
    owner: ec2-user
    group: ec2-user
    mode: '0600'
  when: flask_artifact != ""

- name: Create systemd service for Flask app
  copy:
    dest: /etc/systemd/system/flask_app.service
    content: |
      [Unit]
      Description=Flask Application
      After=network.target postgresql.service 
      Wants=postgresql.service 

      [Service]
      Type=simple
      User=ec2-user
      # This is where your app.py file lives
      WorkingDirectory=/opt/apps/flask_app 

      # IMPORTANT: Ensure ~/.local/bin is included, as pip installs go there.
      Environment=PATH=/usr/local/bin:/usr/bin:/bin:/home/ec2-user/.local/bin
      EnvironmentFile=/opt/apps/flask_app/.env

      # -----------------------------------------------------------------
      # CRITICAL CHANGE: Run the app.py file directly with Python
      # This assumes your main application file is named 'app.py'
      ExecStart=/usr/bin/python3 app.py 
      # -----------------------------------------------------------------

      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
    when: flask_artifact != ""
  become: true

- name: Reload systemd, enable, and start Flask app
  systemd:
    name: flask_app
    state: started
    enabled: true
    daemon_reload: true
  when: flask_artifact != ""
